
#Client Settings
[Client_Settings]
	#BYG Main Menu Panorama.
	Panorama = true
	#BYG's Biome Fog Settings.
	#Applies to "Overworld" ONLY.
	#Allowed Values: DENSEFOGCOLOR, DENSEFOG, FOGCOLOR, OFF
	BiomeFog = "DENSEFOGCOLOR"

