
[Stone_Settings]

	[Stone_Settings.Soapstone]
		#Range: 0 ~ 100
		SoapstoneChance = 10
		#Range: 0 ~ 256
		SoapstoneMaxY = 30
		#Range: 0 ~ 35
		SoapstoneSize = 24

	[Stone_Settings.Scoria_Stone]
		#Range: 0 ~ 100
		ScoriaStoneChance = 10
		#Range: 0 ~ 256
		ScoriaStoneMaxY = 20
		#Range: 0 ~ 35
		ScoriaStoneSize = 24

	[Stone_Settings.Rocky_Stone]
		#Range: 0 ~ 100
		RockyStoneSize = 24
		#Range: 0 ~ 100
		RockyStoneChance = 4
		#Range: 0 ~ 256
		RockyStoneMaxY = 256

#Other Dimension Biomes
[Dimension_Settings]
	#Add external Nether biomes by their registry names in a commented list.
	ExternalNetherBiomes = ""
	#Add external End biomes by their registry names in a commented list.
	ExternalEndBiomes = ""
	#Control the size of nether biomes.
	#Range: 1 ~ 10
	NetherBiomeSize = 2

[Ore_Settings]

	#Pendorite is exclusive to Forest Fault!
	[Ore_Settings.Pendorite]
		#Range: 0 ~ 256
		PendoriteMaxY = 56
		#Range: 0 ~ 16
		PendoriteSize = 4
		#Range: 0 ~ 100
		PendoriteChance = 25

	#Ametrine is exclusive to Guiana Shield!
	[Ore_Settings.Ametrine]
		#Range: 0 ~ 100
		AmetrineChance = 10
		#Range: 0 ~ 256
		AmetrineMaxY = 56
		#Range: 0 ~ 16
		AmetrineSize = 4

#Nether Settings
[Nether_Settings]
	#256 Height. Default is false
	TallNether = false

