
[adjustmentStick]
	allowedMods = ["chineseworkshop"]
	allowedClasses = ["net.minecraft.block.HugeMushroomBlock", "net.minecraft.block.FenceBlock", "net.minecraft.block.WallBlock", "net.minecraft.block.PaneBlock", "net.minecraft.block.StainedGlassPaneBlock", "net.minecraft.block.StairsBlock"]

[gui]
	showConversionJei = true
	showRetextureJei = true

