
#Common configuration settings
[common]
	#Mutant Zombie spawn weight
	#Range: 0 ~ 100
	mutantZombieSpawnWeight = 4
	#Mutant Skeleton spawn weight
	#Range: 0 ~ 100
	mutantSkeletonSpawnWeight = 4
	#Mutant Enderman spawn weight
	#Range: 0 ~ 100
	mutantEndermanSpawnWeight = 3
	#Mutant Creeper spawn weight
	#Range: 0 ~ 100
	mutantCreeperSpawnWeight = 4
	#Mutants will not spawn in the provided dimensions, using their registry name
	#Example - "minecraft:overworld", "minecraft:the_nether" 
	dimensionBlacklist = []

