
[general]
	#True if player UI has plague hearts render when the effect is active.
	"Plague Heart Overlay" = true
	#True if rats flutes can occasionally make a funny sound.
	"Funny Rat Flute Sound" = true

