
[general]

	[general.spawnVanillaChickens]
		#Set this to true to allow vanilla minecraft chickens to continue to spawn/exist. False will prevent vanilla chicken spawning and delete existing ones from the world.
		enabled = false

	[general.horseGestation]
		#Number of ticks for pig gestation. 48000 = 2 Minecraft Days
		#Range: > 1
		days = 48000

	[general.spawnGeneticRabbits]
		#Set this to true to allow genetic minecraft rabbits to continue to spawn/exist. False will prevent genetic rabbit spawning and delete existing ones from the world.
		enabled = true

	[general.spawnGeneticSheep]
		#Set this to true to allow genetic minecraft sheep to continue to spawn/exist. False will prevent genetic sheep spawning and delete existing ones from the world.
		enabled = true

	[general.spawnGeneticCows]
		#Set this to true to allow genetic minecraft cows to continue to spawn/exist. False will prevent genetic cow spawning and delete existing ones from the world, if this is false genetic mooshroom will disappear when sheared
		enabled = true

	[general.spawnVanillaCats]
		#Set this to true to allow vanilla minecraft cats to continue to spawn/exist. False will prevent vanilla cat spawning and delete existing ones from the world.
		enabled = true

	[general.rabbitGestation]
		#Number of ticks for rabbit gestation. 24000 = 1 Minecraft Day
		#Range: > 1
		days = 24000

	[general.spawnVanillaRabbits]
		#Set this to true to allow vanilla minecraft rabbits to continue to spawn/exist. False will prevent vanilla rabbit spawning and delete existing ones from the world.
		enabled = false

	[general.pigGestation]
		#Number of ticks for pig gestation. 48000 = 2 Minecraft Days
		#Range: > 1
		days = 48000

	[general.spawnGeneticPigs]
		#Set this to true to allow genetic minecraft pigs to continue to spawn/exist. False will prevent genetic pig spawning and delete existing ones from the world.
		enabled = true

	[general.wildType]
		# 100 will make all animals spawn as wildtype for their biome, some mutations may be impossible to get. 0 makes animals spawn with almost completely random genes. higher numbers are best since you only need a few mutations to make a big difference
		#Range: > 1
		chance = 90

	[general.spawnGeneticMooshroom]
		#Set this to true to allow genetic minecraft mooshroom to continue to spawn/exist. False will prevent genetic mooshroom spawning and delete existing ones from the world.
		enabled = true

	[general.sheepGestation]
		#Number of ticks for sheep gestation. 48000 = 2 Minecraft Daysy
		#Range: > 1
		days = 48000

	[general.spawnVanillaLlamas]
		#Set this to true to allow vanilla minecraft llamas to continue to spawn/exist. False will prevent vanilla llama spawning and delete existing ones from the world, except for trader llamas
		enabled = false

	[general.spawnVanillaCows]
		#Set this to true to allow vanilla minecraft cows to continue to spawn/exist. False will prevent vanilla cow spawning and delete existing ones from the world.
		enabled = false

	[general.spawnVanillaHorse]
		#Set this to true to allow vanilla minecraft horse to continue to spawn/exist. False will prevent vanilla horse spawning and delete existing ones from the world.
		enabled = true

	[general.cowGestation]
		#Number of ticks for cow and mooshroom gestation. 48000 = 2 Minecraft Days
		#Range: > 1
		days = 48000

	[general.spawnGeneticLlamas]
		#Set this to true to allow genetic minecraft llamas to continue to spawn/exist. False will prevent genetic llama spawning and delete existing ones from the world.
		enabled = true

	[general.llamaGestation]
		#Number of ticks for llama gestation. 48000 = 2 Minecraft Days
		#Range: > 1
		days = 48000

	[general.spawnVanillaMooshroom]
		#Set this to true to allow vanilla minecraft mooshroom to continue to spawn/exist. False will prevent vanilla mooshroom spawning and delete existing ones from the world.
		enabled = false

	[general.spawnVanillaPigs]
		#Set this to true to allow vanilla minecraft pigs to continue to spawn/exist. False will prevent vanilla pig spawning and delete existing ones from the world.
		enabled = false

	[general.spawnGeneticChickens]
		#Set this to true to allow genetic minecraft chickens to continue to spawn/exist. False will prevent genetic chicken spawning and delete existing ones from the world.
		enabled = true

	[general.spawnVanillaSheep]
		#Set this to true to allow vanilla minecraft sheep to continue to spawn/exist. False will prevent vanilla sheep spawning and delete existing ones from the world.
		enabled = false

	[general.catGestation]
		#Number of ticks for pig gestation. 48000 = 2 Minecraft Days
		#Range: > 1
		days = 48000

