
#Mine and Slash Config
[MAIN_CONFIG]

	[MAIN_CONFIG.PLAYER_BASE_STATS]
		#Range: 0.0 ~ 2.147483647E9
		physical_damage = 3.0
		#Range: 0.0 ~ 2.147483647E9
		mana_regen = 0.0
		#Range: 0.0 ~ 2.147483647E9
		critical_hit = 1.0
		#Range: 0.0 ~ 2.147483647E9
		spell_damage_per_level = 0.25
		#Range: 0.0 ~ 2.147483647E9
		physical_damage_per_level = 0.30000001192092896
		#Range: 0.0 ~ 2.147483647E9
		critical_damage_per_level = 0.0
		#Range: 0.0 ~ 2.147483647E9
		energy_regen = 0.0
		#Range: 0.0 ~ 2.147483647E9
		energy_regen_per_level = 7.0
		#Range: 0.0 ~ 2.147483647E9
		health_regen_per_level = 1.0
		#Range: 0.0 ~ 2.147483647E9
		critical_hit_per_level = 0.0
		#Range: 0.0 ~ 2.147483647E9
		mana_regen_per_level = 3.0
		#Range: 0.0 ~ 2.147483647E9
		critical_damage = 0.0
		#Range: 0.0 ~ 2.147483647E9
		magic_shield_regen = 3.0
		#Range: 0.0 ~ 2.147483647E9
		energy = 0.0
		#Range: 0.0 ~ 2.147483647E9
		health_regen = 4.0
		#Range: 0.0 ~ 2.147483647E9
		magic_shield_per_level = 0.0
		#Range: 0.0 ~ 2.147483647E9
		energy_per_level = 125.0
		#Range: 0.0 ~ 2.147483647E9
		health_per_level = 5.0
		#Range: 0.0 ~ 2.147483647E9
		health = 100.0
		#Range: 0.0 ~ 2.147483647E9
		magic_shield = 0.0
		#Range: 0.0 ~ 2.147483647E9
		armor = 10.0
		#Range: 0.0 ~ 2.147483647E9
		mana = 0.0
		#Range: 0.0 ~ 2.147483647E9
		mana_per_level = 50.0
		#Range: 0.0 ~ 2.147483647E9
		spell_damage = 3.0
		#Range: 0.0 ~ 2.147483647E9
		armor_per_level = 5.0
		#Range: 0.0 ~ 2.147483647E9
		magic_shield_regen_per_level = 1.0

	[MAIN_CONFIG.DROPRATES]
		#.
		#Range: 0.0 ~ 2.147483647E9
		AWAKEN_RUNEWORD_DROPRATE = 0.14000000059604645
		#.
		#Range: 0.0 ~ 2.147483647E9
		COMPATIBLE_ITEMS_DROPRATE = 2.0
		#.
		#Range: 0.0 ~ 2.147483647E9
		RUNED_GEAR_DROPRATE = 1.7
		#.
		#Range: 0.0 ~ 2.147483647E9
		MAP_DROPRATE = 0.800000011920929
		#.
		#Range: 0.0 ~ 2.147483647E9
		UNIQUE_DROPRATE = 0.20000000298023224
		#.
		#Range: 0.0 ~ 2.147483647E9
		CURRENCY_DROPRATE = 2.0
		#.
		#Range: 0.0 ~ 2.147483647E9
		LOOTBOX_DROPRATE = 0.05
		#.
		#Range: 0.0 ~ 2.147483647E9
		SPELL_DROPRATE = 4.0
		#.
		#Range: 0.0 ~ 2.147483647E9
		RUNE_DROPRATE = 1.3
		#.
		#Range: 0.0 ~ 2.147483647E9
		UNIQUE_RUNE_DROPRATE = 0.1
		#.
		#Range: 0.0 ~ 2.147483647E9
		GEAR_DROPRATE = 8.0

	[MAIN_CONFIG.GENERAL]
		#.
		#Range: 0.0 ~ 100.0
		TALENT_POINTS_PER_LEVEL = 1.25
		#.
		ONLY_REPAIR_IN_STATION = false
		#.
		#Range: 0.0 ~ 2.147483647E9
		NON_MOD_HEAL_MULTI = 0.1
		#.
		#Range: 0.0 ~ 100.0
		STAT_REQUIREMENTS_MULTI = 1.0
		#.
		#Range: > 0
		MAPS_DROP_AFTER_LEVEL = 10
		#.
		GET_STARTER_ITEMS = true
		#.
		#Range: > 0
		MAXIMUM_WORN_RUNED_ITEMS = 3
		#.
		#Range: 0.0 ~ 1.0
		STOP_DROPS_IF_NON_PLAYER_DOES_DMG_PERCENT = 0.5
		#.
		#Range: 0.0 ~ 2.147483647E9
		UNARMED_ENERGY_COST = 1.5
		#.
		#Range: 0.0 ~ 100.0
		STAT_POINTS_PER_LEVEL = 1.0
		#.
		USE_COMPATIBILITY_ITEMS = true
		#.
		ENABLE_CURRENCY_ITEMS_INSTABILITY_SYSTEM = true
		#.
		#Range: 0.0 ~ 100.0
		PLAYER_HEART_TO_HEALTH_CONVERSION = 1.0
		#.
		#Range: > 0
		MAXIMUM_ITEM_INSTABILITY = 500
		#.
		#Range: 0.0 ~ 2.147483647E9
		NON_MOD_DAMAGE_MULTI = 0.0
		#.
		DISABLE_VANILLA_HP_REGEN = true
		#.
		LEVEL_UPS_COST_TOKEN = false
		#.
		GENERATE_ORES = true
		#.
		DISABLE_DEATH_IN_MAPS = true
		#.
		#Range: > 0
		MAXIMUM_WORN_UNIQUE_ITEMS = 4
		#.
		#Range: > 0
		CURRENCY_DROP_AFTER_LEVEL = 10
		#.
		#Range: > 0
		MAXIMUM_PLAYER_LEVEL = 100
		#.
		RESET_MAP_DIMENSIONS_ON_LOAD = true
		#.
		#Range: 0.0 ~ 2.147483647E9
		EXPERIENCE_MULTIPLIER = 1.0
		#.
		#Range: 0.0 ~ 1.0
		XP_LOSS_ON_DEATH = 0.25
		#.
		ENABLE_CURRENCY_ITEMS_BREAKING_MODIFIED_ITEMS = true
		#.
		#Range: 0.0 ~ 2.147483647E9
		MOB_ENVIRONMENT_DAMAGE_MULTI = 0.2

	[MAIN_CONFIG.RARITY_WEIGHT_CONTAINERS]

		[MAIN_CONFIG.RARITY_WEIGHT_CONTAINERS.CURRENCY]
			#Range: > 0
			RARE_WEIGHT = 5000
			#Range: > 0
			COMMON_WEIGHT = 30000
			#Range: > 0
			MYTHICAL_WEIGHT = 250
			#Range: > 0
			UNCOMMON_WEIGHT = 20000
			#Range: > 0
			EPIC_WEIGHT = 3000
			#Range: > 0
			LEGENDARY_WEIGHT = 1250

		[MAIN_CONFIG.RARITY_WEIGHT_CONTAINERS.ITEM]
			#Range: > 0
			RARE_WEIGHT = 5000
			#Range: > 0
			COMMON_WEIGHT = 30000
			#Range: > 0
			MYTHICAL_WEIGHT = 250
			#Range: > 0
			UNCOMMON_WEIGHT = 20000
			#Range: > 0
			EPIC_WEIGHT = 3000
			#Range: > 0
			LEGENDARY_WEIGHT = 1250

		[MAIN_CONFIG.RARITY_WEIGHT_CONTAINERS.SPELLS]
			#Range: > 0
			RARE_WEIGHT = 5000
			#Range: > 0
			COMMON_WEIGHT = 30000
			#Range: > 0
			MYTHICAL_WEIGHT = 250
			#Range: > 0
			UNCOMMON_WEIGHT = 20000
			#Range: > 0
			EPIC_WEIGHT = 3000
			#Range: > 0
			LEGENDARY_WEIGHT = 1250

		[MAIN_CONFIG.RARITY_WEIGHT_CONTAINERS.RUNES]
			#Range: > 0
			RARE_WEIGHT = 5000
			#Range: > 0
			COMMON_WEIGHT = 25000
			#Range: > 0
			MYTHICAL_WEIGHT = 300
			#Range: > 0
			UNCOMMON_WEIGHT = 16666
			#Range: > 0
			EPIC_WEIGHT = 3600
			#Range: > 0
			LEGENDARY_WEIGHT = 1500

		[MAIN_CONFIG.RARITY_WEIGHT_CONTAINERS.MAPS]
			#Range: > 0
			RARE_WEIGHT = 5000
			#Range: > 0
			COMMON_WEIGHT = 20000
			#Range: > 0
			MYTHICAL_WEIGHT = 375
			#Range: > 0
			UNCOMMON_WEIGHT = 13333
			#Range: > 0
			EPIC_WEIGHT = 4500
			#Range: > 0
			LEGENDARY_WEIGHT = 1875

		[MAIN_CONFIG.RARITY_WEIGHT_CONTAINERS.RUNED_ITEMS]
			#Range: > 0
			RARE_WEIGHT = 5000
			#Range: > 0
			COMMON_WEIGHT = 30000
			#Range: > 0
			MYTHICAL_WEIGHT = 250
			#Range: > 0
			UNCOMMON_WEIGHT = 20000
			#Range: > 0
			EPIC_WEIGHT = 3000
			#Range: > 0
			LEGENDARY_WEIGHT = 1250

		[MAIN_CONFIG.RARITY_WEIGHT_CONTAINERS.MOBS]
			#Range: > 0
			RARE_WEIGHT = 5000
			#Range: > 0
			COMMON_WEIGHT = 30000
			#Range: > 0
			MYTHICAL_WEIGHT = 250
			#Range: > 0
			UNCOMMON_WEIGHT = 20000
			#Range: > 0
			EPIC_WEIGHT = 3000
			#Range: > 0
			LEGENDARY_WEIGHT = 1250

